# Generated by Django 6.0.6 on 2026-08-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_options_route_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['origin', 'destination']},
        ),
    ]
