# Generated by Django 6.0.6 on 2026-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Minibus', 'Minibus')], max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
